### ISSUE TITLE
Contributor Theme Ad Tag Updates

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-theme#14]
### Overview

Ad tags on the contributor theme need to be updated from:
googletag.defineSlot('/7021/fcc.forum/fcc.areavoices'
to:
googletag.defineSlot('/7021/fcc.areavoices'

Looks like the tags are correct on Top News, but not on the contributor theme.
#### Checklist
- [ ] Update ad tags

**Comment by rveitch** [comment]
This is now live.

Production Push: 
http://gitlab.fccinteractive.com/areavoices/areavoices-com/commit/c5a01e1be4378346e9615a8cd7c38fdb236b4993
