### ISSUE TITLE
Numbers added to UND Hockey Blog Comments

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/areavoices-theme#9]
### Overview

Looks like the responses to comments are occasionally getting numbers applied to the comment (see screenshot).
#### Mockups & Examples

![screenshot51](https://cloud.githubusercontent.com/assets/17886062/14262699/5f87e6c4-fa7c-11e5-8983-f7769fefca33.jpg)
### Reference
- [UND Hockey Blog](http://undhockey.areavoices.com/?p=102854)

**Comment by bradenfcc** [comment]
Forgot to mark this as done....so....done!

**Comment by rveitch** [comment]
Updates pushed to production and verified.

**Comment by jgrinsteinner** [comment]
Looks great! Thanks guys!
